name: Deploy and Test

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Install dependencies
        run: |
          npm i
      - name: Compile
        run: |
          npx hardhat compile

      - name: Test
        run: |
          npx hardhat test


    steps:
      - name: Deploy
        # Hard-code user mnemonic
        run: |
          echo "MNEMONIC = ${{secrets.MNEMONIC}}" > .env 
          npx hardhat run --network tomo_testnet scripts/deploy.ts
